# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: ^docs/
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
  - id: golangci-lint

- repo: local
  hooks:
    - id: go-generate
      name: go generate
      language: system
      entry: go generate ./...
      pass_filenames: false
