// Code generated by "qip_type -type RR -package rr"; DO NOT EDIT.

package rr

type RR struct {
	Owner                   string `json:"owner,omitempty"`
	ClassType               string `json:"classType,omitempty"`
	RRType                  string `json:"rrType,omitempty"`
	Data1                   string `json:"data1,omitempty"`
	Publishing              string `json:"publishing,omitempty"`
	TTL                     int    `json:"ttl,omitempty"`
	InfraType               string `json:"infraType,omitempty"`
	InfraFQDN               string `json:"infraFQDN,omitempty"`
	Data2                   string `json:"data2,omitempty"`
	Data3                   string `json:"data3,omitempty"`
	Data4                   string `json:"data4,omitempty"`
	InfraAddr               string `json:"infraAddr,omitempty"`
	IsCreatingReverseZoneRR bool   `json:"isCreatingReverseZoneRR,omitempty"`
	IsDefaultRR             bool   `json:"isDefaultRR,omitempty"`
}
