// Code generated by "qip_type -type V4Subnet -package v4subnet"; DO NOT EDIT.

package v4subnet

type V4Subnet struct {
	SubnetAddress                            string                        `json:"subnetAddress,omitempty"`
	SubnetMask                               string                        `json:"subnetMask,omitempty"`
	NetworkAddress                           string                        `json:"networkAddress,omitempty"`
	SubnetName                               string                        `json:"subnetName,omitempty"`
	SubnetOrg                                string                        `json:"subnetOrg,omitempty"`
	Application                              string                        `json:"application,omitempty"`
	Location                                 V4SubnetLocation              `json:"location,omitempty"`
	Contact                                  V4SubnetContact               `json:"contact,omitempty"`
	HardwareType                             string                        `json:"hardwareType,omitempty"`
	TftpServerName                           string                        `json:"tftpServerName,omitempty"`
	AllowDHCPClientsToModifyDynamicObjectRRs string                        `json:"allowDHCPClientsToModifyDynamicObjectRRs,omitempty"`
	Domains                                  V4SubnetDomains               `json:"domains,omitempty"`
	ShowUsage                                string                        `json:"showUsage,omitempty"`
	CheckUsage                               string                        `json:"checkUsage,omitempty"`
	SubnetDescription                        string                        `json:"subnetDescription,omitempty"`
	SharedNetwork                            string                        `json:"sharedNetwork,omitempty"`
	WarningType                              int                           `json:"warningType,omitempty"`
	WarningPercentage                        float64                       `json:"warningPercentage,omitempty"`
	PreferredDNSServers                      V4SubnetPreferredDNSServers   `json:"preferredDNSServers,omitempty"`
	PreferredTimeServers                     V4SubnetPreferredTimeServers  `json:"preferredTimeServers,omitempty"`
	DefaultRouters                           V4SubnetDefaultRouters        `json:"defaultRouters,omitempty"`
	DefaultDHCPServer                        string                        `json:"defaultDHCPServer,omitempty"`
	DefaultDHCPOptionTemplate                string                        `json:"defaultDHCPOptionTemplate,omitempty"`
	DefaultDHCPPolicyTemplate                string                        `json:"defaultDHCPPolicyTemplate,omitempty"`
	PrimaryInterface                         bool                          `json:"primaryInterface,omitempty"`
	OptionalAttributeList                    V4SubnetOptionalAttributeList `json:"optionalAttributeList,omitempty"`
	AddressTemplate                          string                        `json:"addressTemplate,omitempty"`
	LocalTotalDynamicObjects                 int                           `json:"localTotalDynamicObjects,omitempty"`
	LocalLeasedDynamicObjects                int                           `json:"localLeasedDynamicObjects,omitempty"`
	LocalPercentDynamicObjectsUsed           float64                       `json:"localPercentDynamicObjectsUsed,omitempty"`
}

type V4SubnetLocation struct {
	ID      int    `json:"id,omitempty"`
	Street1 string `json:"street1,omitempty"`
	Street2 string `json:"street2,omitempty"`
	City    string `json:"city,omitempty"`
	State   string `json:"state,omitempty"`
	Zip     string `json:"zip,omitempty"`
	Country string `json:"country,omitempty"`
}

type V4SubnetContact struct {
	ID        int    `json:"id,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName  string `json:"lastName,omitempty"`
	Telephone string `json:"telephone,omitempty"`
	Pager     string `json:"pager,omitempty"`
	Email     string `json:"email,omitempty"`
}

type V4SubnetDomains struct {
	Name []string `json:"name,omitempty"`
}

type V4SubnetPreferredDNSServers struct {
	Name []string `json:"name,omitempty"`
}

type V4SubnetPreferredTimeServers struct {
	Name []string `json:"name,omitempty"`
}

type V4SubnetDefaultRouters struct {
	Name []string `json:"name,omitempty"`
}

type V4SubnetOptionalAttributeList struct {
	Udas   []V4SubnetOptionalAttributeListUdas   `json:"udas,omitempty"`
	Groups []V4SubnetOptionalAttributeListGroups `json:"groups,omitempty"`
}

type V4SubnetOptionalAttributeListUdas struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}

type V4SubnetOptionalAttributeListGroups struct {
	Name string                                    `json:"name,omitempty"`
	Udas []V4SubnetOptionalAttributeListGroupsUdas `json:"udas,omitempty"`
}

type V4SubnetOptionalAttributeListGroupsUdas struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
